---
- name: deploy the iperf3-mux server
  hosts: management
  tasks:

    - name: ensure apt packages are present
      become: true
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - iperf3
        - python3
        - python3-dev
        - python3-setuptools
        - python3-pip

    - name: ensure pip3 packages are present
      become: true
      pip:
        name: "{{ item }}"
        executable: pip3
      loop:
        - twisted

    - name: clone git repo
      git:
        repo: https://github.com/adamkpickering/iperf3-mux.git
        dest: /home/adam/iperf3-mux
        force: true

    - name: link between iperf3-server.service and /etc/systemd/system/iperf3-server.service
      become: true
      file:
        state: link
        src: /home/adam/iperf3-mux/iperf3-server.service
        dest: /etc/systemd/system/iperf3-server.service

    - name: activate service etc
      become: true
      systemd:
        name: iperf3-server
        enabled: true
        state: restarted
        daemon_reload: yes
